#!/usr/bin/env bash

if [[ -z $DOTFILES ]]; then
    DOTFILES="$HOME/.dotfiles"
fi

# Using find to get a list of directories in DOTFILES, excluding hidden ones
STOW_FOLDERS=$(find "$DOTFILES" -mindepth 1 -maxdepth 1 -type d ! -name '.*' -exec basename {} \;)

pushd "$DOTFILES" > /dev/null
for folder in $STOW_FOLDERS
do
    echo "stow $folder"
    stow -D "$folder"
    stow --adopt "$folder"
done
popd > /dev/null

